-- Insert categories one by one
INSERT INTO categories (name, description, icon, gradient) VALUES ('Beauty & Salon', 'Hair, skincare & beauty treatments', 'Scissors', 'bg-gradient-to-br from-pink-500 to-rose-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Wellness Services', 'Health, fitness & wellness', 'Activity', 'bg-gradient-to-br from-green-500 to-teal-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Food & Beverages', 'Fresh food & drink delivery', 'Coffee', 'bg-gradient-to-br from-orange-500 to-red-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Home Services', 'Cleaning, repairs & maintenance', 'Home', 'bg-gradient-to-br from-yellow-500 to-orange-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Electronics & Gadgets', 'Repair, installation & tech support', 'Zap', 'bg-gradient-to-br from-purple-500 to-pink-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Education & Training', 'Tutoring, coaching & skill development', 'BookOpen', 'bg-gradient-to-br from-indigo-500 to-blue-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Pet Services', 'Pet care, grooming & training', 'Heart', 'bg-gradient-to-br from-green-400 to-blue-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Event Services', 'Photography, decoration & planning', 'Camera', 'bg-gradient-to-br from-red-500 to-pink-500');
INSERT INTO categories (name, description, icon, gradient) VALUES ('Transportation', 'Delivery, moving & logistics', 'Truck', 'bg-gradient-to-br from-gray-500 to-gray-700');

-- Add service_type column if it doesn't exist
ALTER TABLE services ADD COLUMN IF NOT EXISTS service_type VARCHAR(20) DEFAULT 'platform';

-- Insert services one by one
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Beauty & Salon' LIMIT 1), 'Hair Cut & Styling', 'Beauty & Salon', 'Hair Services', 'Professional haircut with styling', 499, '45 mins', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=300&fit=crop', 4.8, 256, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Beauty & Salon' LIMIT 1), 'Hair Coloring', 'Beauty & Salon', 'Hair Services', 'Professional hair coloring service', 1299, '2 hours', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=300&fit=crop', 4.7, 189, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Beauty & Salon' LIMIT 1), 'Facial Treatment', 'Beauty & Salon', 'Skincare', 'Deep cleansing facial treatment', 899, '60 mins', 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=300&fit=crop', 4.9, 142, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Beauty & Salon' LIMIT 1), 'Manicure & Pedicure', 'Beauty & Salon', 'Nail Care', 'Complete nail care service', 699, '90 mins', 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=300&fit=crop', 4.6, 98, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Beauty & Salon' LIMIT 1), 'Bridal Makeup', 'Beauty & Salon', 'Makeup', 'Professional bridal makeup service', 2499, '3 hours', 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=300&fit=crop', 4.9, 167, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Wellness Services' LIMIT 1), 'Yoga Session', 'Wellness Services', 'Fitness', 'Personal yoga training session', 799, '60 mins', 'https://images.unsplash.com/photo-1506126613408-eca07ce68e71?w=400&h=300&fit=crop', 4.8, 156, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Wellness Services' LIMIT 1), 'Physiotherapy', 'Wellness Services', 'Medical', 'Professional physiotherapy session', 999, '45 mins', 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop', 4.7, 134, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Wellness Services' LIMIT 1), 'Full Body Massage', 'Wellness Services', 'Massage', 'Relaxing Swedish massage therapy', 1299, '60 mins', 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=300&fit=crop', 4.9, 189, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Food & Beverages' LIMIT 1), 'Birthday Cake', 'Food & Beverages', 'Bakery', 'Custom birthday cake delivery', 1299, '2 hours', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop', 4.8, 89, 'vendor_product');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Food & Beverages' LIMIT 1), 'Fresh Juice', 'Food & Beverages', 'Beverages', 'Fresh fruit juice delivery', 199, '15 mins', 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&h=300&fit=crop', 4.5, 67, 'vendor_product');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Food & Beverages' LIMIT 1), 'Event Catering', 'Food & Beverages', 'Catering', 'Professional catering for events', 2999, '4 hours', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop', 4.7, 142, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Home Services' LIMIT 1), 'House Cleaning', 'Home Services', 'Cleaning', 'Deep cleaning service for homes', 899, '3 hours', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop', 4.5, 234, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Home Services' LIMIT 1), 'Plumbing Repair', 'Home Services', 'Repairs', 'Professional plumbing services', 499, '1 hour', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=300&fit=crop', 4.6, 189, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Home Services' LIMIT 1), 'AC Service', 'Home Services', 'Maintenance', 'Air conditioner cleaning and maintenance', 699, '2 hours', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=300&fit=crop', 4.4, 156, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Electronics & Gadgets' LIMIT 1), 'Mobile Repair', 'Electronics & Gadgets', 'Device Repair', 'Smartphone repair service', 799, '2 hours', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop', 4.4, 145, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Electronics & Gadgets' LIMIT 1), 'TV Installation', 'Electronics & Gadgets', 'Installation', 'Professional TV mounting service', 599, '1 hour', 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop', 4.6, 123, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Electronics & Gadgets' LIMIT 1), 'Computer Support', 'Electronics & Gadgets', 'Tech Support', 'Software troubleshooting and setup', 499, '1 hour', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=300&fit=crop', 4.3, 98, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Education & Training' LIMIT 1), 'Math Tutoring', 'Education & Training', 'Academic', 'Personal math tutoring session', 599, '60 mins', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400&h=300&fit=crop', 4.8, 178, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Education & Training' LIMIT 1), 'Guitar Lessons', 'Education & Training', 'Skills', 'Learn guitar with professional instructor', 799, '60 mins', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop', 4.7, 134, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Education & Training' LIMIT 1), 'Career Coaching', 'Education & Training', 'Professional', 'Professional career guidance session', 999, '90 mins', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop', 4.6, 89, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Pet Services' LIMIT 1), 'Dog Grooming', 'Pet Services', 'Grooming', 'Professional dog grooming service', 899, '2 hours', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=300&fit=crop', 4.6, 156, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Pet Services' LIMIT 1), 'Dog Training', 'Pet Services', 'Training', 'Basic obedience training for dogs', 1299, '60 mins', 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=300&fit=crop', 4.8, 112, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Pet Services' LIMIT 1), 'Pet Sitting', 'Pet Services', 'Care', 'Professional pet sitting service', 599, '4 hours', 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=300&fit=crop', 4.5, 167, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Event Services' LIMIT 1), 'Photography', 'Event Services', 'Photography', 'Professional event photography', 2999, '4 hours', 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=400&h=300&fit=crop', 4.9, 234, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Event Services' LIMIT 1), 'Party Decoration', 'Event Services', 'Decoration', 'Complete party decoration service', 1999, '3 hours', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=300&fit=crop', 4.7, 145, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Event Services' LIMIT 1), 'Event Planning', 'Event Services', 'Planning', 'Complete event coordination service', 4999, '8 hours', 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=300&fit=crop', 4.8, 98, 'platform');

INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Transportation' LIMIT 1), 'Delivery Service', 'Transportation', 'Delivery', 'Same-day delivery service', 199, '1 hour', 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=300&fit=crop', 4.4, 345, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Transportation' LIMIT 1), 'Home Shifting', 'Transportation', 'Moving', 'Complete household moving service', 3999, '6 hours', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop', 4.5, 189, 'platform');
INSERT INTO services (category_id, title, category, subcategory, description, price, duration, image_url, rating, total_reviews, service_type) VALUES ((SELECT id FROM categories WHERE name = 'Transportation' LIMIT 1), 'Bulk Transport', 'Transportation', 'Logistics', 'Commercial goods transportation', 2499, '4 hours', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop', 4.3, 123, 'platform');